### ISSUE TITLE
Adding a LICENSE file or heading to the README?

### ISSUE THREAD

**Issue by mithro** [hughski/colorhug1-firmware#1]
It looks like most of this code is released under GPLv2 (by looking at the headers at the top of various files). It would be good to either;
- add a LICENSE/COPYING file to the repository
- add a short section to the README with those details

If I get around to it today, I'll send you a pull request with this done but in case I get distracted I thought it would be good to log an issue.

**Comment by hughsie** [comment]
Yup, the code is all GPLv2+

**Comment by hughsie** [comment]
Hmm, I found https://github.com/hughski/colorhug1-firmware/blob/master/COPYING -- did you mean a different project or is this not enough?
